# Generated by Django 6.0 on 2026-01-05 15:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locataire',
            options={'verbose_name_plural': 'Locataires'},
        ),
        migrations.CreateModel(
            name='Quittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generation', models.DateTimeField(default=django.utils.timezone.now)),
                ('mois', models.CharField(max_length=15)),
                ('annee', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=4)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locataires.locataire')),
            ],
            options={
                'verbose_name_plural': 'Quittances',
                'ordering': ['-date_generation'],
            },
        ),
    ]
