# Generated by Django 6.0 on 2026-01-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0002_alter_locataire_options_quittance'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='adresse',
            field=models.CharField(default='Adresse à définir', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quittance',
            name='mois',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='quittance',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
