# Generated by Django 6.0 on 2026-01-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0003_locataire_adresse_alter_quittance_mois_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='date_entree',
            field=models.DateField(default='2025-01-01', verbose_name="Date d'entrée dans les lieux"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quittance',
            name='date_debut_periode',
            field=models.DateField(default='2025-01-01', verbose_name='Début de période'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quittance',
            name='date_fin_periode',
            field=models.DateField(default='2025-01-01', verbose_name='Fin de période'),
            preserve_default=False,
        ),
    ]
