# Generated by Django 6.0 on 2026-01-06 22:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0004_locataire_date_entree_quittance_date_debut_periode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quittance',
            name='date_paiement',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date du paiement'),
        ),
        migrations.AlterUniqueTogether(
            name='quittance',
            unique_together={('locataire', 'mois', 'annee')},
        ),
    ]
