# Generated by Django 6.0 on 2026-01-06 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0005_quittance_date_paiement_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quittance',
            unique_together=set(),
        ),
    ]
