# Generated by Django 6.0 on 2026-01-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0006_alter_quittance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quittance',
            name='annee',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='quittance',
            name='mois',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')]),
        ),
    ]
