# Generated by Django 6.0 on 2026-01-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0007_alter_quittance_annee_alter_quittance_mois'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quittance',
            name='date_debut_periode',
            field=models.DateField(blank=True, null=True, verbose_name='Début de période'),
        ),
        migrations.AlterField(
            model_name='quittance',
            name='date_fin_periode',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de période'),
        ),
        migrations.AlterUniqueTogether(
            name='quittance',
            unique_together={('locataire', 'mois', 'annee')},
        ),
    ]
