# Generated by Django 6.0 on 2026-01-07 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0008_alter_quittance_date_debut_periode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='documents_locataires/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='locataires.locataire')),
            ],
            options={
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
