# Generated by Django 6.0 on 2026-01-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0009_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='charges_mensuelles',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quittance',
            name='charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Charges mensuelles (€)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quittance',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Loyer mensuel (€)'),
        ),
    ]
