# Generated by Django 6.0 on 2026-01-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0010_locataire_charges_mensuelles_quittance_charges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quittance',
            name='charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Charges mensuelles (€)'),
        ),
    ]
