# Generated by Django 6.0 on 2026-01-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0011_alter_quittance_charges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locataire',
            old_name='charges_mensuelles',
            new_name='charges',
        ),
    ]
