# Generated by Django 6.0 on 2026-01-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0012_rename_charges_mensuelles_locataire_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='quittance',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
