# Generated by Django 6.0 on 2026-01-07 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0013_quittance_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quittance',
            old_name='montant',
            new_name='loyer',
        ),
    ]
