# Generated by Django 6.0 on 2026-01-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0014_rename_montant_quittance_loyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quittance',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Montant payé (€)'),
        ),
    ]
