# Generated by Django 6.0 on 2026-01-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0015_quittance_montant_paye'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quittance',
            options={'ordering': ['locataire__nom', 'annee', 'mois'], 'verbose_name_plural': 'Quittances'},
        ),
    ]
